const JWT_SECRET = '64b47cd7d12efe505db55667';
const STATUS_OK = 200;
const INVAILD_ID = 'NotValidId';
const ERROR_CODE_UNIQUE = 11000;
const BAD_REQUEST_CODE = 400;

module.exports = {
  STATUS_OK,
  INVAILD_ID,
  JWT_SECRET,
  ERROR_CODE_UNIQUE,
  BAD_REQUEST_CODE,
};
